apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle-backend
  namespace: wordle-game
spec:
  replicas: 2 # 2 repliki - aby w razie awarii podu płynnie podmienić
  strategy:
    type: RollingUpdate # strategia rolling update - wymiana starej wersji aplik na nową
    rollingUpdate:
      maxSurge: 1 # o ile może przekroczyć liczbe podów przy wymianie
      maxUnavailable: 0 # w momencie aktualizacji żaden pod nie może niedostępny
  selector:
    matchLabels:
      app: wordle-backend
  template:
    metadata:
      labels:
        app: wordle-backend
    spec:
      # SecurityContext 
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      
      # InitContainer - czeka aż baza danych zacznie odpowiadać
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z -v -w3 wordle-db-svc 5432; do echo "Czekanie na baze danych..."; sleep 2; done;']
      
      containers:
      - name: backend
        image: wworonecka/wordle-backend:latest # CI/CD
        ports:
        - containerPort: 3000
        resources: # limity zasobów
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        env: # pobieranie z secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: wordle-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wordle-secrets
              key: jwt-secret
        - name: MQTT_BROKER
          valueFrom:
            configMapKeyRef:
              name: wordle-config
              key: MQTT_BROKER
        # Probes
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3

# Główny kontroler - zawiera sondy sprawdzające endpointy /health i /ready