# konfigurację kontenerów (kto, ile replik, jakie limity)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle-frontend
  namespace: wordle-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordle-frontend
  template:
    metadata:
      labels:
        app: wordle-frontend
    spec:
      containers:
      - name: frontend
        image: wworonecka/wordle-frontend:latest
        ports:
        - containerPort: 80