# frontend
apiVersion: v1
kind: Service
metadata:
  name: wordle-frontend-svc
  namespace: wordle-game
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: wordle-frontend
---
# backend
apiVersion: v1
kind: Service
metadata:
  name: wordle-backend-svc
  namespace: wordle-game
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: wordle-backend
---
# baza - dostępna tylko wewnątrz
apiVersion: v1
kind: Service
metadata:
  name: wordle-db-svc
  namespace: wordle-game
spec:
  ports:
  - port: 5432
  selector:
    app: wordle-db
  clusterIP: None
---
# cache dostępna tylko wewnątrz
apiVersion: v1
kind: Service
metadata:
  name: wordle-cache-svc
  namespace: wordle-game
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: wordle-cache