name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/wordle-backend:latest

    - name: Set up Kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/db-statefulset.yaml
        kubectl apply -f k8s/services.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/network-policy.yaml
        kubectl apply -f k8s/pdb.yaml

    - name: Verify Rollout Status # Wymóg: sprawdzenie statusu rolloutu
      run: |
        kubectl rollout status deployment/wordle-backend -n wordle-game
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/